### ISSUE TITLE
few questions on how to use the package

### ISSUE THREAD

**Issue by demetrius-mp** [ciscoheat/sveltekit-rate-limiter#10]
It is my first time implementing rate limiting on sveltekit (actually never did it with any other technology), so i have some questions that are probably trivial:

1. in the example below you say "unique cookie name for this limiter". this means i must define the rate limiter cookie name on a "per-route" basis, right?

```ts
const limiter = new RateLimiter({
  // A rate is defined as [number, unit]
  IP: [10, 'h'], // IP address limiter
  IPUA: [5, 'm'], // IP + User Agent limiter
  cookie: {
    // Cookie limiter
    name: 'limiterid', // Unique cookie name for this limiter <---------
    secret: 'SECRETKEY-SERVER-ONLY', // Use $env/static/private
    rate: [2, 'm'],
    preflight: true // Require preflight call (see load function)
  }
});
```

2. can i use the same `RateLimiter` instance in 2 routes (assume i do not have the cookie limiter enabled)? for example, can i have an `AuthRateLimiter` in `$lib/server/auth-rate-limiter.ts`, and use it in `/routes/sign-up/+page.server.ts` and `/routes/reset-password/+page.server.ts`?

**Comment by markanator** [comment]
1. A unique cookie name, in general, not per route. Let's say you had a session cookie called `"__sid"`, you wouldn't use that same cookie name for for this limiter.
2. You could create a new file in `$lib/server` that exports a single rate limit instance to be used throughout your app. But, you can also follow this advice and create specific limiters for particular use cases. Each limiter would need a unique cookie name.
