### ISSUE TITLE
How to create multiple limits for the same limiter

### ISSUE THREAD

**Issue by conorvenus** [ciscoheat/sveltekit-rate-limiter#11]
I want to limit either 1 login per second, or 100 logins per hour for example, but `[100, 'h']` is unsatisfactory, because it allows the user to send all 100 of their requests in a single second if they wanted to, which could overload the server.

Hence, I also want both checks - also, if this library is capable of doing that, please could you add this as one of the primary examples on the `README.md`?

**Comment by ciscoheat** [comment]
Maybe it can be added as an array of rates for the built-in limiters. I have to experiment a bit.

**Comment by ciscoheat** [comment]
Added now in 0.6.0, specify the rates as an array and it should work. Can you confirm that it does?

**Comment by ciscoheat** [comment]
Closing this, as the tests are passing.
