### ISSUE TITLE
Feature request: Allow additonal arguments to be passed to `limiter.isLimited` / `limiter.check`

### ISSUE THREAD

**Issue by oscarhermoso** [ciscoheat/sveltekit-rate-limiter#6]
## Feature request: Allow additonal arguments to be passed to `limiter.isLimited` / `limiter.check`

I want to implement a custom rate limiter for my app that takes into consideration some information that was not in the original request event, for example:

```ts
// include some info that is not in the RequestEvent
const status = await limiter.check(event, 'email@test.com');
```

I've skimmed the code and doesn't look too hard to implement, just need to pass arguments through a few points and update type definitions, assuming this is a feature that looks OK to implement.

<details><summary>Code</summary>
<p>

https://github.com/ciscoheat/sveltekit-rate-limiter/blob/0466070755d8458f3defb376df33b01888288df2/src/lib/server/index.ts#L256

https://github.com/ciscoheat/sveltekit-rate-limiter/blob/0466070755d8458f3defb376df33b01888288df2/src/lib/server/index.ts#L272-L274

https://github.com/ciscoheat/sveltekit-rate-limiter/blob/0466070755d8458f3defb376df33b01888288df2/src/lib/server/index.ts#L278

https://github.com/ciscoheat/sveltekit-rate-limiter/blob/0466070755d8458f3defb376df33b01888288df2/src/lib/server/index.ts#L409

</p>
</details> 

## Workaround

I was able to implement a work-around for now, by extending the type definition of the SvelteKit RequestEvent.

### `$lib/server/rate-limit.ts`

```ts
import type { RequestEvent } from '@sveltejs/kit';
import {
	RetryAfterRateLimiter,
	type Rate,
	type RateLimiterPlugin,
} from 'sveltekit-rate-limiter/server';

declare module '@sveltejs/kit' {
	/**
	 * The sveltekit-rate-limiter check function only takes a single argument, the RequestEvent.
	 * This is a workaround to make additional arguments available to the RateLimiter.
	 */
	export interface RequestEvent {
		_rate_limit_args?: { email: string };
	}
}

export class EmailAddressRateLimiter implements RateLimiterPlugin {
	readonly rate: Rate;

	constructor(rate: Rate) {
		this.rate = rate;
	}

	// eslint-disable-next-line @typescript-eslint/require-await
	async hash(event: RequestEvent) {
		return event._rate_limit_args?.email || false;
	}
}

```

### `$routes/+page.server.ts`

```ts
// usage:
const limiter = new RetryAfterRateLimiter({
	IP: [10, 'h'],
	IPUA: [5, 'm'],
	plugins: [new EmailAddressRateLimiter([5, 'm'])],
});

export const actions = {
	default: async (event) => {

		// check auth, etc.

		const _rate_limit_args = { email: 'email@test.com' };
		
		const status = await limiter.check({ ...event, _rate_limit_args });

		if (status.limited) {
			// 429 response
		}

		// ...rest of the action
	},
};

```

**Comment by ciscoheat** [comment]
Added now in 0.5.0, check the readme for an example: https://github.com/ciscoheat/sveltekit-rate-limiter?tab=readme-ov-file#custom-data-for-the-limiter (and let me know if it works well!)

**Comment by oscarhermoso** [comment]
Woah, super awesome. Not every day you raise a GitHub issue and see a new release has been pushed the next morning

Looks like it's working great! (although I'm knee-deep in a Lucia auth migration from v2 to v3 - my app is not in a working state to test any more than type definitions right now)

TypeScript 

```ts
import type { RequestEvent } from '@sveltejs/kit';
import { type Rate, type RateLimiterPlugin } from 'sveltekit-rate-limiter/server';

// pretty verbose
export class EmailAddressRateLimiter implements RateLimiterPlugin {
	readonly rate: Rate;

	constructor(rate: Rate) {
		this.rate = rate;
	}

	// eslint-disable-next-line @typescript-eslint/require-await
	async hash(_: RequestEvent, extraData: { email: string }) {
		return extraData.email || false;
	}
}

// 
const email_rate_limiter = (rate: Rate): RateLimiterPlugin<{ email: string }> => {
	return {
		rate,
		// eslint-disable-next-line @typescript-eslint/require-await
		hash: async (_, extraData) => extraData.email || false,
	};
};
```

**Comment by ciscoheat** [comment]
No problem, it was a useful feature and an update was overdue. :) I understand the problem with type inference in classes, so I'm glad it works with both versions. I think the classes are small enough to not be overly verbose. Added `MaybePromise` to the interfaces in 0.5.1.

**Comment by oscarhermoso** [comment]
Thanks Andreas!
